phpredis/phpredis

README.markdown
According to https://github.com/phpredis/phpredis/search?utf8=%E2%9C%93&q=OPT_READ_TIMEOUT&type=Code it's Redis::OPT_READ_TIMEOUT
=> Fix Redis::OPT_READ_TIMOUT typo

redis_array.c, redis_array_impl.c
As of around 2013, `zend_hash_quick_find` has an assertion that will crash PHP if it is called with the `nKeyLength` argument set to 0:
http://lxr.php.net/xref/PHP_5_6/Zend/zend_hash.c?a=true&h=862#867
This causes any use of RedisArray to crash on a debug build (tested on PHP 5.6.5 on OSX). It will not crash on a non-debug build because the assertions are not "live".
```php
$r = new RedisArray(['localhost:6379']);
```
Crashes with:
```
Assertion failed: (nKeyLength != 0), function zend_hash_quick_find, file /Users/michaelmaclean/.phpbrew/build/php-5.6.5/Zend/zend_hash.c, line 867.
[1]    72715 abort      php test.php
```
This fixes that issue.
=> Fix zend_hash_quick_find usage to avoid assertion failures

redis_commands.c
Because it is not defined HAVE_REDIS_IGBINARY in 2918 line.
=> Fix Set igbinary as serializer.

redis.c
```
(gdb) run ...
...
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff1366eec in redis_sock_get (id=<optimized out>, redis_sock=redis_sock@entry=0x7fffffffaea0,
no_throw=no_throw@entry=1) at /usr/local/src/phpredis/redis.c:442
warning: Source file is more recent than executable.
442	    *redis_sock = (RedisSock *)Z_RES_P(socket)->ptr;
...
(gdb) bt
#0  0x00007ffff1366eec in redis_sock_get (id=<optimized out>, redis_sock=redis_sock@entry=0x7fffffffaea0,
no_throw=no_throw@entry=1) at /usr/local/src/phpredis/redis.c:442
#1  0x00007ffff1367b60 in zim_Redis___destruct (execute_data=0x7ffff1a14d90, return_value=0x7fffffffaff0)
at /usr/local/src/phpredis/redis.c:663
#2  0x00000000007876d0 in zend_call_function (fci=fci@entry=0x7fffffffb050, …
```
=> Fix segmentation fault on PHP 7.0.0RC5

cluster_library.c
The socket stream in RedisCluster.seeds leave unclosed incorrectly.
Which cause crash when creating RedisCluster repeatedly，even if call close function in the loop.
And the error message show "Couldn't map cluster keyspace using any provided seed"
=> Fix bug of unclosed socket stream in RedisCluster's construction

redis_cluster.c
For #828 
- rename argument structures for cluster part
- get rid of LD errors:
- multiple definition of `arginfo_scan'
- multiple definition of `arginfo_kscan'
=> Quick fix for PHP-5.2:

cluster_library.c
The loss of updating the 'slotstail' field will result in the loss of slot ranges if one master is in charge of several  separate slot-ranges, and then segment fault will happen.
=> Bugfix in node_add_slot_range procedure

redis.c
add_class_constants twice in the  PHP_MINIT_FUNCTION method, php_session_register_module method of repeated calls.
in phpinfo(), "Registered save handlers" displayed "redis rediscluster redis rediscluster".
=> Fixed method call problem causes session handler to display two times

library.c, redis.c, redis_cluster.c
The null assignment to spl_ce_RuntimeException was causing a "missing symbol" error for other extensions that depend on the extern definitions in [`spl_exceptions.h`](https://github.com/php/php-src/blob/master/ext/spl/spl_exceptions.h). Similar to the Redis extension, PDO also has a function that resolves the SPL class on-demand (see: [here](https://github.com/php/php-src/blob/php-5.6.23/ext/pdo/pdo.c#L74)); however, they use a [static decl](https://github.com/php/php-src/blob/php-5.6.23/ext/pdo/pdo.c#L36) to avoid conflicting with SPL.
The second commit in this PR is just cleaning up an unused extern decl I came across. It's not related to the issue at hand.
See: https://github.com/mongodb/mongo-php-driver/issues/353
=> Use static declarations for spl_ce_RuntimeException decl

redis.c
Now it is difficult to set dbNumber after server reply... This PR partially fixed issue #836 (negative values are definitely incorrect).
I also added checking for negative port in `slaveof` command and memory allocation after `argc` checking in `rawcommand`
@michael-grunder, review please :)
=> Partial fix for #836 + additional checking params

library.c, redis_commands.c
The fixes are limited to what are covered by tests/TestRedis.php
Command used to detect memory leaks (Anything mentioning redis):
```bash
USE_ZEND_ALLOC=0 ZEND_DONT_UNLOAD_MODULES=1 valgrind --leak-check=full \
php --php-ini php.ini tests/TestRedis.php
```
- USE_ZEND_ALLOC uses malloc/free/etc instead of Zend's custom allocator
- ZEND_DONT_UNLOAD_MODULES allows valgrind to print the file and line
numbers for a shared library (this extension)
- about valgrind: http://valgrind.org/docs/manual/quick-start.html
While the allocated memory would be cleaned up after the end of a request,
memory leaks might cause problems for long-running CLI scripts dealing
with hundreds of thousands of keys.
zval_get_string will do one of the following for a ZVAL:
1. If it is of type IS_STRING, it will increase …
=> Fix various memory leaks in allocating strings.

redis.c, redis_commands.c, redis_session.c
If zval_(ptr_)dtor wasn't called on the converted values later,
it would be a memory leak (lasting only until the request was over).
Follow up to #918
=> Fix other leaks; use zval_get_* where it makes code shorter.

common.h, redis.c, redis_array.c, redis_array_impl.c, redis_cluster.c, redis_commands.c
ZEND_HASH_FOREACH_VAL now works with zval * instead of zval **
=> WIP: php7 compatibility

common.h, redis.c, redis_array.c, redis_cluster.c, redis_commands.c, redis_commands.h
Redefine zend_get_parameters_array macro for working with `zval *` instead of `zval **`
=> WIP: php compatibility

redis_array.c, redis_array_impl.c
Using ZVAL_STRINGL instead of ZVAL_STRING for string literals + using stack variables instead of allocated by MAKE_STD_ZVAL
=> RedisArray refactoring

config.w32
Before this commit, building 32-bit with igbinary enabled in
Visual Studio 2015 failed,
since igbinary/igbinary.h wasn't in the include path
(VS2015 x86 Native Tools command prompt)
CHECK_HEADER_ADD_INCLUDE would add pecl/phpredis/../igbinary to the include path. Then, it would search for pecl/phpredis/../igbinary/igbinary/igbinary.h (etc), which didn't exist when I built it. (pecl/phpredis/../igbinary/igbinary.h does)
Pecls were installed in a pecl folder adjacent to (same level as)
php-7.0.9-src folder.
```
C:\php-sdk\bin\phpsdk_setvars.bat
buildconf
configure --disable-all --enable-cgi --enable-session --enable-igbinary --enable-redis-igbinary
```
The commit in this PR can be cherry-picked to develop as well, since the config.w32 has the same bug.
=> php7 - Properly add igbinary to the include path in windows

cluster_library.c, redis.c, redis_array.c, redis_cluster.c, redis_commands.c
The 'l' specifier now expects a zend_long instead of a long
for zend_parse_parameters.
=> php7 compatibility

redis.c
1/ add module dependency to not allow to load redis extension when igbinary is needed and disable
STANDARD_MODULE_HEADER_EX exists since 5.1.0
(probably the ZEND_MODULE_API_NO >= 20010901 can be removed... 4.2.0...)
2/ display serializers info
3/ use PHP_FE_END
Was {NULL, NULL, NULL} up to 5.3.6
PHP_FE_END exists since 5.3.7 and is define differently (as { NULL, NULL, NULL, 0, 0 })
=> Various minor

redis.c, redis_array.c, redis_array.h, redis_array_impl.c
Using custom objects instead of zend list entry for storing RedisArray data structure.
This avoid double hash lookup every call
=> redis_array_object

cluster_library.c, tests/RedisClusterTest.php
This PR fixes an issue when running LUA commands that don't return any values in a cluster context. In these cases, Redis will return a Null Bulk String as specified in the protocol:
> RESP Bulk Strings can also be used in order to signal non-existence of a value using a special format that is used to represent a Null value. In this special format the length is -1, and there is no data, so a Null is represented as:
> 
> "$-1\r\n"
> 
> This is called a Null Bulk String.
> 
> The client library API should not return an empty string, but a nil object, when the server replies with a Null Bulk String. For example a Ruby library should return 'nil' while a C library should return NULL (or set a special flag in the reply object), and so forth.
Right now, this case is not handled and it causes …
=> Fix Null Bulk String response parsing in cluster library

common.h, library.c, redis.c
In pipeline mode all commands are now stored in the buffer
the memory for which is allocated with emalloc.
There is no need to use a linked list.
=> refactoring

README.markdown
1. delete the duplicate "install"
2. update the homebrew-php link
=> fixed duplicate 'install' typo and update the homebrew-php link

common.h, redis.c, redis_commands.c, tests/RedisTest.php
This PR fixes issues #946 and #1166.
=> Using ZVAL_DEREF macros for dereference input variables.

redis.c
Reopen #1163 against develop branch
This is incomplete, writing arginfo for everything in a single PR
would be difficult for reviewers.
This focuses on string operations and some common commands for
redis 1.0.
The macro's arguments are:
ZEND_BEGIN_ARG_INFO_EX(name, _unused, return_reference, required_num_args)
For #1055 (Still a lot of work)
This is based on what was written in README, not 100% sure if it matches
the code.
=> Add arginfo for ReflectionMethod to redis for some commands

cluster_library.c, library.c, redis_commands.c
This change allows us to not use one more `convert_to_string`
=> Don't use convert_to_string in redis_hmget_cmd

common.h, redis.c, redis_cluster.c, redis_commands.c, redis_commands.h
Move building `script` command logic to `redis_build_script_cmd`
and use it in Redis and RedisCluster objects.
Fix memory leak in `cluster_raw_cmd` when `cluster_cmd_get_slot` fails.
=> Issue #1245

library.c
This change allows to use empty string as persistant_id
=> Issue #1238

.gitmodules, .travis.yml, cluster_library.c, common.h, config.m4, library.c, library.h, package.xml, redis.c, redis_cluster.c, redis_commands.c, tests/RedisTest.php
This commit is adding support of data compression.
LZF was choosen because it small and fast and Redis server uses it.
Since [pecl package](https://pecl.php.net/package/lzf) doesn't provide
lzf.h file after installing, LZF library was added as submodule.
Another algorythms may be easely added by analogy with serializers.
TODO: unit-tests for different data types.
=> Issue #1048

common.h, library.c, redis.c, redis_commands.c
Here is our access model `Redis -> LVS -> Redis`, we use `LVS` as load balance for the Redis server.
We occur the `read error on connection` when the `LVS` kick off the connection without `fin`, so it makes sense to keepalive？and phpredis would be reconnected.
=> FEATURE: Add tcp_keepalive option to redis sock

cluster_library.c
yesterday i used RedisCluster connect my redis cluser, code like this:
$hosts = [
"10.1.15.22:7100",
"10.1.15.22:7101",
];
array_walk($hosts, function(&$val) {
$val = trim($val);
});
$rc = new RedisCluster(null, $hosts, null, null, true);
this code runs normally on php5.x but error on php7.x, error info is:
PHP Fatal error: Uncaught RedisClusterException: Couldn't map cluster keyspace using any provided seed in /opt/php/test.php:14
Stack trace:
#0 /opt/php/test.php(14): RedisCluster->__construct(NULL, Array, NULL, NULL, true)
#1 {main}
thrown in /opt/php/test.php on line 14
tracing the source code of phpredis, i found the element of ht_seeds is a referent in function cluster_init_seeds on php7.x environment.
i fixed this problem and re-compiled the redis extension, and the code runs …
=> the element of z_seeds may be a reference on php7

redis_session.c
Use zend_string for storing auth and prefix members and disallow to use empty string as session name
=> Refactor redis session

tests/RedisTest.php
Needed to be able to run build on a offline server, which is common practice in downstream distribution.
=> skip online test

redis_session.c, redis_session.h, tests/RedisTest.php, tests/regenerateSessionId.php
This PR is based on PR #1289 and fixes the issue described [here](https://github.com/phpredis/phpredis/issues/1267#issuecomment-365632260).
@asharpe Thanks for the great work!
=> Session locking: Fix regenerate ID bug (PHP5, proxy handler)

redis_session.c, redis_session.h, tests/RedisTest.php, tests/regenerateSessionId.php
Thanks for the session locking functionality!
I work with software that uses `session_regenerate_id(true)` during login and I was unable to login with the code as it was.  After noticing that the memcache extension doesn't suffer from this issue I cobbled this together.
I've only compiled this on php 5.3, 5.4 and 5.6
=> Allow session locking to work with session_regenerate_id (see #1267)

tests/RedisTest.php
I was running the tests on a local machine but don't have openssl installed so I _think_ it ended up generating empty NULL ids in the tests.
=> Fallback if we don't have openssl

redis.c
see #1337 
I didn't check other methods than `connect` & `pconnect` and I did not make the default value available for reflection
=> only the first arg of connect and pconnect is required

INSTALL.markdown, README.markdown, package.xml
This PR split the installation instruction out from README into a INSTALL dedicated page (which is a common practice in lot of projects)
Notice: the INSTALL file have role="src" (not "doc"), as there is no need to install this file, once installed, it is no more useful.
I also add link for Fedora / RHEL / CentOS official packages (other distro may be added later, by someone who know about them)
P.S. I also wanted to enligth the temporary situation in Fedora, where users may choose between v3 and v4 (different package name).
=> split INSTALL and add more instructions

tests/RedisTest.php
When running test suite with PHP 7.3.0alpha1
```
...
testExpireAt                                                   
Warning: time() expects exactly 0 parameters, 1 given in /dev/shm/BUILD/php73-php-pecl-redis4-4.1.0~RC1/NTS/tests/RedisTest.php on line 455
[FAILED]
testSetEx                                                      [PASSED]
...
```
=> Fix: Warning: time() expects exactly 0 parameters, 1 given ... (php 7.3)

.travis.yml
This should get travis builds working again after redis-trib.rb was deprecated: https://github.com/antirez/redis/commit/d222eda9f089f6605d755777c32132cb8cad76c9
It also switches to the ``trusty`` dist, because travis was strongly warning that ``precise`` was going away. When ``precise`` does go away, there will not be a way to test php 5.3.
=> travis: Use default dist; fix redis-trib.rb error

INSTALL.markdown
Except for Homebrew (Linux like a clone), there's also package manager MacPorts (FreeBSD like a clone) which is having the package for php-redis
=> There are two big package managers on OS X

cluster_library.c, cluster_library.h, common.h, library.c, redis.c
Fixes #1222 
Fixes #1418 
I did the following stuff on a timeout:
- Force disconnect the current socket, so even a persistent connection is cleared (so no chance for illegal data to be returned the next time).
- Change the lazy_connect logic to reset this correctly. Without this change, the loop in `cluster_send_command` will run very quickly without really retrying to connect.
I'm not really sure if this last change is correct in all cases, but it seems to work for me.
=> Reset the socket after a timeout to make sure no wrong data is received

library.c, redis.c, redis_cluster.c
Right before Redis 5.0 was released, the api was changed to send
message ids as BULK instead of STATUS replies.
=> Update STREAM API to handle STATUS -> BULK reply change

library.c
This commit fix 2  [-Wunused-variable] when LZF is not available
Still one warning which seems a good catch from GCC
```
In file included from /usr/include/php/Zend/zend.h:33:0,
from /usr/include/php/main/php.h:35,
from /work/GIT/phpredis/common.h:1,
from /work/GIT/phpredis/library.c:5:
/work/GIT/phpredis/library.c: In function 'redis_read_xclaim_response':
/usr/include/php/Zend/zend_alloc.h:163:26: warning: 'id' may be used uninitialized in this function [-Wmaybe-uninitialized]
#define efree(ptr)       _efree((ptr) ZEND_FILE_LINE_CC ZEND_FILE_LINE_EMPTY_CC)
^~~~~~
/work/GIT/phpredis/library.c:1409:11: note: 'id' was declared here
char *id;
^~
```
From library.c
`          if ((li != 2 || (id = redis_sock_read(redis_sock, &idlen TSRMLS_CC)) == NULL) ||`
So, if `li == 2` id is not set.
=>  build warnings

common.h, library.c, library.h, redis_commands.c
This should fix the XCLAIM issue on 32-bit PHP installs.
I'm not 100% sure we can rely on INT64_MAX being defined in Windows but it seems like we can since PHP defines it in `win32/php_stdint.h` only under certain conditions.  We'll want to verify that this is correct before officially releasing 4.2.0.
I tried to protect the user from passing us invalid data while allowing them to pass us the option in pretty much any possible way (float, long, or string).
=> 32bit xclaim fix

redis_session.c
Make sure we free any existing session lock key if we're going to
update it.  Otherwise, we will leak that memory.
=> Fix a memory leak when regenerating IDs

redis.c, redis_cluster.c
Hi, when I make it in PHP74, I get a compile error.
#ref: https://github.com/php/php-src/commit/8939c4d96b8382abe84f35e69f4f6ebd6f0f749d#r30609734
The flag was automatically determined, there was no need to set it explicitly.
This change is compatible with all PHP versions, and it fixes compilation error in PHP74.
=> Remove useless ZEND_ACC_[C|D]TOR.

README.markdown
Missing parentheses in the zRangeByScore method example
=> Syntax error in zRangeByScore method example

INSTALL.markdown
The homebrew-php tap no longer exists. Best option for homebrew users is PECL.
=> Remove outdated homebrew instructions

cluster_library.c, cluster_library.h, common.h, library.c, library.h, redis.c, redis_cluster.c, redis_commands.c, tests/RedisClusterTest.php, tests/RedisTest.php
Adds an option to process the actual strings in simple string replies as
opposed to translating them to `true`.  This only applies to
`rawCommand` and `eval` because as far as I know know vanilla Redis
command attaches any information besides `OK` to simple string replies.
Addresses #1550
=> Adds OPT_REPLY_LITERAL for rawCommand and EVAL

redis.c
Right now it is not possible to pass NULL as the persistent_id if strict
types are enabled.  This change allows the argument to be NULL.
Addresses issue #1551
=> Allow persistent_id to be passed as NULL with strict_types enabled.

cluster_library.c
Connections are stashed via redis_sock_disconnect so if RedisCluster
doesn't explicitly call that for slaves then pooling is never used for
those connections.
Fixes #1568
=> WIP: Enable pooling for cluster slave nodes.

redis.c
The HAVE_SPL symbol is defined in PHP to indicate the presence of the spl extension. Since PHP 5.3 the spl extension is always availabe and since PHP-7.4 the HAVE_SPL symbol has also been removed.
=> Remove HAVE_SPL

INSTALL.markdown
Remove Fedora <= 28 (redis v3) which is now EOL
Fedora 31 already have php-pecl-redis5 version 5.0.0RC1
php-pecl-redis4 will be removed from F31 repo
and php-pecl-redis5 added to F29/F30 repo after 5.0.0GA
=> Update Fedora installation instructions

.travis.yml, Changelog.md, common.h, config.m4, library.c, redis.c, redis_commands.c, tests/RedisTest.php
**Zstd** is "usually" faster and give better results than **lzf**
From some benchmark (for quite a big file, ie "php" itself)
```
Compress functions:
gzdeflate           zlib: 5103144 => 1823040 (64% saved) in 0,216
bzcompress           bz2: 5103144 => 1747961 (65% saved) in 0,320
lz4_compress         lz4: 5103144 => 2638214 (48% saved) in 0,011
lzf_compress         lzf: 5103144 => 2614515 (48% saved) in 0,021
snappy_compress   snappy: 5103144 => 2671118 (47% saved) in 0,015
zstd_compress      zstd1: 5103144 => 2023044 (60% saved) in 0,017
zstd_compress      zstd3: 5103144 => 1856634 (63% saved) in 0,027
zstd_compress      zstd9: 5103144 => 1724733 (66% saved) in 0,154
zstd_compress     zstd22: 5103144 => 1569291 (69% saved) in 1,401
```
=> Add support for Zstd compression

cluster_library.c, cluster_library.h, common.h, library.c, library.h, php_redis.h, redis.c, redis_array.c, redis_array.h, redis_array_impl.c, redis_array_impl.h, redis_cluster.c, redis_cluster.h, redis_commands.c, redis_commands.h, redis_session.c
This macro are no more used since 7.0, and have been totally removed in 8.
Mostly a result of 
```
sed -e 's/ TSRMLS_CC//' -i *.c *.h 
sed -e 's/TSRMLS_C//' -i *.c *.h 
sed -e 's/ TSRMLS_DC//' -i *.c *.h 
sed -e 's/TSRMLS_D/void/' -i *.c *.h 
```
=> cleanup TSRMLS_* usage

common.h, redis.c
Since 5.0.0, trying to connect to redis on a high enough port number gives a "No such file or directory" error. Various internal type casts end up treating port numbers from 2^15 as negative, which awkwardly triggers the unix-socket-path behaviour. This is a regression from 4.3.0.
```
$ redis-server --daemonize yes --port 32768
$ php -r '(new Redis())->connect("127.0.0.1", 32768);'
```
The port number comes in to phpredis internals as a `long`, gets forced to `unsigned short` when passed to `redis_sock_create`, then cast to `short` when put in the `RedisSock` structure; at that point, half of possible values effectively become negative thanks to two's-complement.
Amazingly, this always worked before: the string formatting that builds up the `host` arg to give to `php_stream_xport_create` …
=> Fix "No such file or directory" when connecting to ports >= 32768

Changelog.md, package.xml
"Latest" means most recent, whereas "last" means that nothing will follow.
=> Fix wording in changelog: 'latest' should be 'last'

README.markdown
Spent much time understand the issue in my code with redis when migrating from php 7.2 (redis 4.1.1) to php 7.3 (redis 5.0.2) so I thought this correction of the documentation may help others.
=> Updated README with correct return value for ping command

Changelog.md
https://github.com/phpredis/phpredis/issues/1563 notes that it a breaking change (it did break my app, since I used string comparison to check if redis connection is alive), but changelog only says that an additional argument was added.
=> Explicitly state that ping return type changed

.travis.yml, README.markdown, library.c, library.h, tests/RedisTest.php
In PR #1602 we decided to use unsigned short for storing RedisSock->port
but in previous release I reverted that change. In this PR I changed
signatire of redis_sock_create to prevent unneccecary convertion of types.
=> Issue #1664

redis_cluster.c
These methods accept a single argument, not two arguments.
(cluster_cmd_get_slot accepts one argument)
=> Fix proto comments for host_port in RedisCluster

redis_session.c
This fix protects `session.gc_maxlifetime` from an integer overflow or from a value <= 0 as a negative expire in Redis is an error.  
I'm not totally sure if this is the correct strategy, as we could instead just treat the value as a `zend_long` but a timeout >= INT_MAX is nearly 70 years in the future so strikes me as rather meaningless.
@yatsukhnenko What do you think?
Addresses #1694
=> Issue.1694 session lifetime

README.markdown
While reviewing the README for information on `popen`, I found that some of the functions listed in the doc were missing deprecation notices. I went through the [deprecated aliases](https://github.com/phpredis/phpredis/blob/develop/redis.c#L447-L476) and updated the notes in the README for those that appear to have been missed.
This also removes how `substr` is described as deprecated as it was inconsistent with the rest of the document.
=> Update README with missing deprecation notes

config.w32
The sentinel sources were added to config.m4 in https://github.com/phpredis/phpredis/commit/c94e28f1ebabdfceb722ad78eff75ce4fc57f5a3#diff-788d457a20b110cc38e571dec9ddc68c
They should be added to config.w32 as well.
Otherwise compiling on Windows fails with
```
redis.obj : error LNK2019: unresolved external symbol create_sentinel_object referenced in function zm_startup_redis
redis.obj : error LNK2001: unresolved external symbol redis_sentinel_ce
redis.obj : error LNK2001: unresolved external symbol redis_sentinel_functions
x64\Release\php_redis.dll : fatal error LNK1120: 3 unresolved externals
```
=> Update config.w32 with sentinel sources

tests/RedisTest.php
Also explicitly add `json.so` if we're manually finding extensions for session tests.
=> Issue.1714 json session tests

library.c
Sanity check for redis_sock->stream before closing.
=> Issue #1721

.travis.yml, tests/RedisArrayTest.php, tests/RedisClusterTest.php, tests/RedisTest.php, tests/TestRedis.php, tests/TestSuite.php
Right now cloning the repo and running unit tests will all fail if the
Redis/RedisCluster instances aren't configured with the password
'phpredis'.
This commit simply makes authentication during the tests optional via a
command-line argument.
=> Make unit test authentication configurable

cluster_library.c, redis_array.c, redis_cluster.c
```
/builddir/build/BUILD/php-pecl-redis5-5.2.2/NTS/redis_array.c: In function 'zim_RedisArray_mget':
/builddir/build/BUILD/php-pecl-redis5-5.2.2/NTS/redis_array.c:944:55: warning: format '%ld' expects argument of type 'long int', but argument 4 has type 'zend_long' {aka 'int'} [-Wformat=]
944 |             key_len = snprintf(kbuf, sizeof(kbuf), "%ld", Z_LVAL_P(data));
|                                                     ~~^
|                                                       |
|                                                       long int
|                                                     %d
/builddir/build/BUILD/php-pecl-redis5-5.2.2/NTS/redis_array.c: In function 'zim_RedisArray_mset':
/builddir/build/BUILD/php-pecl-redis5-5.2.2/NTS/redis_array.c:1070:55: warning: format …
```
=> fix [-Wformat=] warning on 32-bit

config.m4
I found this bug at configuring.
The condition `"PHP_REDIS_JSON" != "no"` is always true regardless of variable `$PHP_REDIS_JSON`.
So, we cannot configure without json's dependency.
This PR maybe related to Isuue #1745
=> bugfix: PHP_REDIS_JSON parameter at configure
