- config.w32
- library.c
- redis_commands.h
- tests/RedisTest.php
Two fixes for VC14. The test fix is generic and should be applied to the other branches as well.
> VC14 fixes (2) and a test fix

- library.c
There are two main reason to cause "read error on connecion". 
1. PHP has a [bug](https://github.com/php/php-src/pull/1456) of checking liveness of a connection. It may 
have a false positive judgement when a connection is indeed closed.
2. phpredis does not check if the redis command is sent successfully or not.
1. Modify library.c and set errno to EWOULDBLOCK before any php_stream_eof. This will trigger the PHP bug.
2. Create test.php
```
<?php
$rds = new Redis();
try {
$ret = $rds->pconnect("127.0.0.1", 6379);
if ($ret == false) {
echo "Connect return false";
exit;
}
echo "Press any key to continue ...";
fgetc(STDIN);
var_dump($rds->get("hellophpredis"));
} catch (Exception $e) {
var_dump ($e);
}
?>
```
3. Run `php test.php`
4. Login redis and `client kill` the test connection
5. …
> Work around PHP bug of liveness checking

- library.c
- redis.c
Fixes 2 leaks when using EVAL / EVALSHA
> memory leak fixes

- redis_session.c
This pull request is referred to issue #740
> Fix problem with rediscluster storage

- redis.c
> Initialize init entry "redis.clusters.persistent"

- library.c
> Redis::redis_sock_read_bulk_reply refactoring

- redis_array_impl.c
> replace emalloc+memcpy with estrndup

- redis.c
> Partial fix for #836 + additional checking params

- library.c
- redis_array_impl.c
- redis_commands.c
- redis_session.c
Based on the [article](https://www.facebook.com/notes/facebook-engineering/three-optimization-tips-for-c/10151361643253920)
> integer_length optimization

- cluster_library.c
- cluster_library.h
- common.h
- library.c
- library.h
- redis.c
- redis_array.c
- redis_array_impl.c
- redis_cluster.c
- redis_commands.c
Implementation of ZEND_HASH_FOREACH_VAL macro for php7 compatibility
> WIP: php7 compatibility

- redis.c
- tests/RedisTest.php
I merged lines `redis.c 858-859` because it seems not so longer.
> fixed #942

- .travis.yml
> TravisCI: run tests for RedisArray class

- redis_array.c
- redis_array.h
- redis_array_impl.c
Store redis instances in zval* instead of zval**
> RedisArray refactoring

- .travis.yml
- cluster_library.c
- library.c
- php_redis.h
- redis_cluster.c
> php7 compatibility

- cluster_library.c
- common.h
- library.c
- library.h
- redis.c
- redis_array_impl.c
- redis_cluster.c
- redis_commands.c
- tests/RedisTest.php
Added gc attribute to zend_string (for zend_string_release).
Added function zval_get_string and replace convert_to_string with it.
> zval_get_string

- .travis.yml
- library.c
- redis.c
> Fix segfault in testSerializerIGBinary

- tests/RedisClusterTest.php
- tests/RedisTest.php
`testSession` may fail until PR #1063 merged
> TravisCI: session

- cluster_library.c
- cluster_library.h
- library.c
- library.h
- redis.c
- redis_cluster.c
- redis_commands.c
- tests/TestRedis.php
Still WIP, it seems there is some other bad cast (redis_serialize)
> fix #1074 bad type cast

- php_redis.h
117L: PHP_METHOD(Redis, zRangeByLex);
119L: PHP_METHOD(Redis, zRangeByLex);
> Remove dupliate code

- README.markdown
- php_redis.h
- redis.c
- redis_cluster.c
- redis_cluster.h
- redis_commands.c
- tests/RedisTest.php
> Issue #1087

- common.h
- redis.c
- tests/RedisTest.php
@michael-grunder, this is still WIP but I need your reviewing at this point
> Allow mixing multi and pipeline modes

- library.c
- redis.c
- tests/RedisClusterTest.php
- tests/RedisTest.php
This should solve the issues people are having in #1211.
> Pipe multi warning revert

- cluster_library.c
- cluster_library.h
- common.h
- library.c
- redis.c
- redis_cluster.c
- redis_commands.c
- redis_session.c
Following fields were changed: err, prefix, persistent_id, auth
> Use zend_string to store strings in RedisSock

- redis.c
- redis_cluster.c
- redis_commands.c
- redis_commands.h
- tests/RedisArrayTest.php
- tests/RedisTest.php
> Update EXISTS to handle multiple keys

- README.markdown
- redis_commands.c
- tests/RedisTest.php
Mostly documentation (gross :smiley:) but contains a small fix having to do with an invalid COUNT argument.
> Geocmds documentation

- README.markdown
Some markdown fixes. Note that two spaces at the end of a line is markdown for a line break
> Markdown fixes

- tests/RedisTest.php
This test covers https://github.com/phpredis/phpredis/issues/1284
> add test for zRangeByLex method

- redis_session.c
* Use zend_string for storing auth and prefix members
* Allocate redis_session_lock_status structure jointly with redis_pool
* Remove redis_pool_new function
> Refactor redis session

- README.markdown
- redis_commands.c
- redis_commands.h
- tests/RedisTest.php
Implements STORE and STOREDIST for GEORADIUS
> Issue.1334

- package.xml
> Typo in notes

- common.h
- redis.c
- redis_array.c
- redis_cluster.c
- redis_commands.c
- redis_commands.h
Handle ASYNC parameter in flushdb and flushall methods
> Issue.1302

- tests/RedisTest.php
- tests/getSessionData.php
- tests/startSession.php
This PR adds tests for the TTL issue referenced in #1354.
Luckily this issue gets fixed by PR #1351, Thanks to @hongboliu!
Currently I have not merged the changes of @hongboliu into my feature branch. So Travis will fail.
> Tests for TTL reset on session access

- tests/RedisClusterTest.php
- tests/RedisTest.php
- tests/TestSuite.php
- tests/getSessionData.php
- tests/regenerateSessionId.php
- tests/startSession.php
As #1357 is already merged I created a new PR.
I refactored some session test to work also with RedisCluster.
> Refactored session tests to work also with Redis cluster

- tests/RedisTest.php
exec("php ...")  seems a bad idea.
Can be something different according to install options
More we may need to pass some options to enable the newly built extension
With this PR, current behavior is preserved (and slightly improved)
And we can override its value
Usage example:
```
export TEST_PHP_EXECUTABLE=/path/to/php
export TEST_PHP_ARGS="-n -d extension=igbinary.so -d extension=$PWD/modules/redis.so"
$TEST_PHP_EXECUTABLE $TEST_PHP_ARGS  tests/TestRedis.php
Note: these tests might take up to a minute. Don't worry :-)
Using PHP version 7.1.18 (64 bits)
/modules/redis.so
Testing class Redis
testMinimumVersion                                             [PASSED]
testPing                                                       [PASSED]
....
testSession_ttl_resetOnRead …
```
> use PHP_BINARY instead of php and allow override

- README.markdown
This PR makes the example codes in README easy-to-read.
> Highlight example codes in README

- README.markdown
I found no info regarding session locking in the docs. Please review the values, as I am not sure of them. Thank you.
> Added subsection of PHP Session handler: "Session locking".

- redis.c
Will improve error message in #1397 case
> session is required

- README.markdown
Based on #1422 we should add a hint regarding support of session locking feature.
> Added hint for session locking support

- library.c
The main purpose of this PR is to consume all data including \r\n in a loop and check result of all php_stream_read operations. Also this PR is related to #1442
> Refactor redis_sock_read_bulk_reply

- cluster_library.c
- library.c
- redis_cluster.c
- tests/RedisTest.php
This appears to work and not leak and/or corrupt memory in PHP 5 and PHP 7.  I will be happy when we can finally remove PHP5 support though. 🤣
> Masters info leakfix

- redis_cluster.c
Free redis response since adding it to our array duplicates the data
anyway.
Addresses #1460
> Fix RedisCluster keys memory leak

- README.markdown
fixes https://github.com/phpredis/phpredis/issues/1467
See https://github.com/phpredis/phpredis/blob/3b56b7db33343f0852e41db9bff5a7880a4cc688/common.h#L1101-L1115
> Updated xrange, xrevrange, xpending types

- README.markdown
https://redis.io/topics/streams-intro
> Add example for $ = last_id and > for not consumed messages yet

- redis_session.c
Same as #1421, but without tests and dependencies on tcpkill.
> Sessions: Breaking the lock acquire loop in case of network problems

- cluster.markdown
- cluster_library.c
- cluster_library.h
- common.h
- library.c
- library.h
- redis.c
- redis_cluster.c
- redis_session.c
This PR is related to #1363.
I don't like version from `cluster-auth` branch and it has many conflicts with `develop` branch so I created new one :smile:
> RedisCluster auth

- redis_commands.c
- tests/RedisTest.php
Adds support for XGROUP CREATE ... MKSTREAM, and support at all for XGROUP DESTROY.
> Xgroup updates

- README.markdown
This note should probably be added to all such commands.
> Note that SCAN is a "directed node" command in RedisCluster

- php_redis.h
- redis.c
- redis_cluster.c
- redis_cluster.h
- redis_commands.c
- redis_commands.h
- tests/RedisTest.php
> Implement GEORADIUS_RO and GEORADIUSBYMEMBER_RO

- README.markdown
- common.h
- library.c
- redis.c
The work is not finished yet but the main idea is clear :)
> Persistent connections pool

- .gitignore
- php_redis.h
- redis.c
- redis_cluster.c
- redis_cluster.h
- redis_commands.c
- redis_commands.h
- tests/RedisTest.php
ZPOPMIN/ZPOPMAX BZPOPMIN/BZPOPMAX
> Issue 1509

- redis_array.c
- redis_array.h
- redis_array_impl.c
Wrap all calls of `call_user_function` into `ra_call_user_function`
where AUTH command sended before function call.
> Issue #1508

- redis_array.c
> Handle references in MGET

- cluster.markdown
Fix grammatical error about the cluster description
> fix typo of cluster description

- redis_commands.c
In strict_type mode `Redis::setOption` requires the second argument
to be of type `string`. This throws a TypeError for some options,
even when using built-in constants
The type of `value` argument of setOption has been changed to
`mixed` to prevent the error.
> Prevent TypeError when using built-in constants in `setOption`. Fixes #1538

- README.markdown
The current example does not work correctly.
> Fix example how to create a stream with a new group

- common.h
- library.c
- redis.c
- redis_commands.c
- tests/RedisTest.php
This PR adds support of JSON serializer.
Users wait it for the years :smile:
> JSON serializer

- library.c
Add server address to exception message.
> Issue #1523

- README.markdown
- library.c
This PR is related to issue #1314
> Allow to specify server address as schema://host

- redis.c
- redis_cluster.c
- redis_commands.c
- redis_commands.h
- tests/RedisClusterTest.php
- tests/RedisTest.php
> Allow PING to take an optional argument.

- redis_commands.c
- tests/RedisTest.php
Change the way we accept COUNT and BLOCK such that a user can pass NULL
to mean "no value".  This is technically a breaking change, since
previously the value `-1` was used for "no value".
Fixes #1560
> Make the XREADGROUP optional COUNT and BLOCK arguments nullable.

- cluster_library.c
- cluster_library.h
- library.c
- library.h
- redis.c
- redis_cluster.c
- tests/RedisTest.php
> xInfo response format

- config.m4
- library.c
- redis.c
- tests/RedisTest.php
Check in config.m4 doesn't work
> Issue #1577

- cluster_library.c
> Fix overallocation in directed cluster MULTIBULK handling.

- cluster.markdown
Fixed minor error in documentation
> Fix cluster.markdown

- redis_session.c
Use `redis_sock` to store `auth` and `prefix` for session.
Use `redis_sock_auth` insted of `redis_pool_member_auth`.
> Refactor redis_session

- library.c
Set error message and fix memory leak.
> Issue #1643

- README.markdown
Documentation for HyperLogLogs as per the Redis Docs https://redis.io/commands#hyperloglog
> Hyper log logs

- redis_session.c
Allow to specify schema for session handler.
> Issue #1657

- Changelog.md
- INSTALL.markdown
Updating documentation to reflect Zstd support added in #1582
> Update docs for Zstd

- library.c
Sending AUTH+PING uniqid in pipeline and checking that response equals to uniqid
> Issue #1668

- cluster_library.c
- cluster_library.h
- redis_cluster.c
- redis_session.c
Fix for issue 1680 sessions not using slots cache
> Enable slot caching for session cluster

- cluster_library.c
- redis_commands.c
Fixes two memory leaks.  For some reason PHP isn't always reporting these, so I'm going to look for more w/valgrind.
Addresses #1701
> Fix a couple of memory leaks in Redis/RedisCluster

- cluster_library.c
- cluster_library.h
> Initial commit of ASK redirection fix

- redis.c
- tests/RedisTest.php
Add TYPE param to SCAN command.
Arginfo wasn't updated so this change isn't breaking change :)
> Issue #1646

- .travis.yml
- README.markdown
- config.m4
- library.c
- redis.c
- redis_commands.c
- redis_commands.h
- redis_sentinel.c
- redis_sentinel.h
- sentinel.markdown
- sentinel_library.c
- sentinel_library.h
- tests/RedisSentinelTest.php
- tests/TestRedis.php
I'm not sure about `getMasterAddrByName`. It returns result as array `[host, port]`, maybe string `host:port` would be better?
TODO: documentation, more tests
> Add RedisSentinel class and tests

- library.c
Again, not sure in which branch should this be applied.
> set initial value to make gcc happy [-Wmaybe-uninitialized]

- README.markdown
> Fix documentation to show lPush and rPush are variadic.
